version: '3'
services:
  dev:
    image: openjdk:15-jdk
    volumes:
      - .:/usr/src/kongo
      - ./../gradle-6.3:/opt/gradle
      - gradlehome:/var/gradle
    working_dir: /usr/src/kongo
    command: bash --init-file init.sh
volumes:
  gradlehome:
    external: true
