* project
[[https://www.instaclustr.com/instaclustr-kongo-iot-logistics-streaming-demo-application/][kongo project]]
[[https://github.com/instaclustr/kongo2.git][kongo2 git]]
* how to build
using gradle
start from openjdk image, add gradle
use gradle_all not only bin, some jar are missing in 
(not using docker image jdk + gradle)
*** mount two directories
- one for gradle
- one for kongo

** kongo1
renamed package to kongo1
** kongo2
first initialize gradle project then clone repo
* Things to do
*** TODO use multi-project gradle
*** DONE setup docker volume
    CLOSED: [2020-05-09 Sat 22:36]
for gradle cache
Environment options
You can customize many aspects about where build scripts, settings, caches, and so on through the options below. Learn more about customizing your build environment.
-g, --gradle-user-home
    Specifies the Gradle user home directory. The default is the .gradle directory in the user’s home directory.
*** TODO Continuous Build

Continuous Build allows you to automatically re-execute the requested tasks when task inputs change.

For example, you can continuously run the test task and all dependent tasks by running:

$ gradle test --continuous
